services:
  ollama-deepseek-r1:
    image: ollama/ollama
    container_name: ollama-deepseek-r1
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: always
    command: ["ollama", "run", "deepseek-ai/DeepSeek-R1-Distill-Qwen-32B"]

  ollama-deepseek-coder:
    image: ollama/ollama
    container_name: ollama-deepseek-coder
    ports:
      - "11435:11434"  # Cambiamos el puerto para evitar conflictos
    volumes:
      - ollama_data:/root/.ollama
    restart: always
    command: ["ollama", "run", "deepseek-ai/DeepSeek-Coder-V2-Instruct"]

volumes:
  ollama_data:
    driver: local