version: '3.8'

services:
  ollama-deepseek-r1:
    image: ollama/ollama
    container_name: ollama-deepseek-r1
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    restart: always
    entrypoint: ["/bin/sh", "-c"]
    command: |
      ollama pull deepseek-ai/DeepSeek-R1-Distill-Qwen-32B &&
      sleep 5 &&
      ollama serve

  ollama-deepseek-coder:
    image: ollama/ollama
    container_name: ollama-deepseek-coder
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11435:11434"  # Evitar conflicto de puertos
    restart: always
    entrypoint: ["/bin/sh", "-c"]
    command: |
      ollama pull deepseek-ai/DeepSeek-Coder-V2-Instruct &&
      sleep 5 &&
      ollama serve

volumes:
  ollama_data:
