services:
  ollama-deepseek-r1:
    image: ollama/ollama
    container_name: ollama-deepseek-r1
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    restart: always
    entrypoint: ["/bin/sh", "-c"]
    command: ["ollama pull deepseek-ai/DeepSeek-R1-Distill-Qwen-32B && ollama serve"]

  ollama-deepseek-coder:
    image: ollama/ollama
    container_name: ollama-deepseek-coder
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11435:11434"  # Cambia el puerto para evitar conflicto
    restart: always
    entrypoint: ["/bin/sh", "-c"]
    command: ["ollama pull deepseek-ai/DeepSeek-Coder-V2-Instruct && ollama serve"]

volumes:
  ollama_data:
