version: '3.8'

services:
  deepseek-r1:
    build: ./deepseek-r1
    environment:
      - MODEL_NAME=deepseek-ai/deepseek-r1-33b-chat
      - QUANTIZATION=awq
      - API_KEY=${R1_API_KEY}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 2
              capabilities: [gpu]
    ports:
      - "8000:8000"
    volumes:
      - models:/root/.cache/huggingface/hub

  deepseek-coder:
    build: ./deepseek-coder
    environment:
      - MODEL_NAME=deepseek-ai/deepseek-coder-33b-instruct
      - QUANTIZATION=awq
      - API_KEY=${CODER_API_KEY}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 2
              capabilities: [gpu]
    ports:
      - "8001:8000"
    volumes:
      - models:/root/.cache/huggingface/hub

#  nginx:
#    image: nginx:latest
#    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
#      - ./nginx/ssl_options.conf:/etc/nginx/ssl_options.conf
#      - certbot-etc:/etc/letsencrypt
#    ports:
#      - "80:80"
#      - "443:443"
#    depends_on:
#      - deepseek-r1
#      - deepseek-coder
#
#  certbot:
#    image: certbot/certbot
#    volumes:
#      - certbot-etc:/etc/letsencrypt
#      - ./certbot/renew-hook.sh:/etc/renew-hook.sh
#    command: certonly --standalone --non-interactive --agree-tos --email ${CERTBOT_EMAIL} -d ${DOMAIN} --keep-until-expiring --pre-hook "nginx -s stop" --post-hook "nginx -c /etc/nginx/nginx.conf"

volumes:
  models:
#  certbot-etc: