services:
  deepseek-r1:
    build: ./deepseek-r1
    environment:
      - MODEL_NAME=deepseek-ai/DeepSeek-R1-Distill-Qwen-32B
      - QUANTIZATION=gptq
      - API_KEY=${R1_API_KEY}
      - HUGGING_FACE_TOKEN=${HUGGING_FACE_TOKEN}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 2
              capabilities: [gpu]
    ports:
      - "8000:8000"
    volumes:
      - models:/root/.cache/huggingface/hub

  deepseek-coder:
    build: ./deepseek-coder
    environment:
      - MODEL_NAME=deepseek-ai/DeepSeek-Coder-V2-Instruct
      - QUANTIZATION=awq
      - API_KEY=${CODER_API_KEY}
      - HUGGING_FACE_TOKEN=${HUGGING_FACE_TOKEN}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 2
              capabilities: [gpu]
    ports:
      - "8001:8000"
    volumes:
      - models:/root/.cache/huggingface/hub
volumes:
  models: