services:
  deepseek-r1:
    build: ./deepseek-r1
    environment:
      - MODEL_NAME=deepseek-ai/DeepSeek-R1-Distill-Qwen-32B
      - API_KEY=${R1_API_KEY}
      - HUGGING_FACE_TOKEN=${HUGGING_FACE_TOKEN}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - RAY_DISABLE_CUSTOM_ALL_REDUCE=True
      - MAX_CONCURRENT_WORKERS=1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 2
              capabilities: [gpu]
    shm_size: '10gb'
    ports:
      - "8000:8000"
    volumes:
      - models:/root/.cache/huggingface/hub

  deepseek-coder:
    build: ./deepseek-coder
    environment:
      - MODEL_NAME=deepseek-ai/DeepSeek-Coder-V2-Instruct
      - API_KEY=${CODER_API_KEY}
      - HUGGING_FACE_TOKEN=${HUGGING_FACE_TOKEN}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - RAY_DISABLE_CUSTOM_ALL_REDUCE=True
      - MAX_CONCURRENT_WORKERS=1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 2
              capabilities: [gpu]
    shm_size: '10gb'
    ports:
      - "8001:8000"
    volumes:
      - models:/root/.cache/huggingface/hub

volumes:
  models:
